### ISSUE TITLE
Error when using crested.pl.patterns.contribution_scores with multiple class_labels

### ISSUE THREAD

**Issue by lldelisle** [aertslab/CREsted#46]
### Report

Hi,
Here is the error I got:
```
2024-10-17T10:27:48.582322+0200 INFO Calculating contribution scores for 4 class(es) and 2 region(s).
Region: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:40<00:00, 20.50s/it]
2024-10-17T10:28:29.579581+0200 ERROR The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):

  File "/home/ldelisle/scripts/scitas_sbatchhistory/2024/20241002_tryCREest/20241016_plots_with_model.py", line 125, in <module>
    crested.pl.patterns.contribution_scores(
    │       │  │        └ <function contribution_scores at 0x7f0011a067a0>
    │       │  └ <module 'crested.pl.patterns' from '/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/pl/patter...
    │       └ <module 'crested.pl' from '/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/pl/__init__.py'>
    └ <module 'crested' from '/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/__init__.py'>

  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/pl/patterns/_contribution_scores.py", line 95, in contribution_scores
    _check_contrib_params(zoom_n_bases, scores, class_labels, sequence_labels)
    │                     │             │       │             └ ['chr19:37739111-37741225', 'chr19:37873331-37875445']
    │                     │             │       └ Index(['whatever1-TileSize-100-normMethod-rc',
    │                     │             │                'whatever2-TileSize-100-normMethod-rc', 'whatever3-TileSize-100-normMethod-r...
    │                     │             └ array([[[[ 2.72991872e-11, -5.19204575e-11,  1.16542938e-11,
    │                     │                          3.49388816e-11],
    │                     │                        [ 9.11343310e-12, -3.590969...
    │                     └ 500
    └ <function _check_contrib_params at 0x7f00117db880>
> File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/utils/_logging.py", line 42, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (500, array([[[[ 2.72991872e-11, -5.19204575e-11,  1.16542938e-11,
           │                  3.49388816e-11],
           │                [ 9.11343310e-12, -3....
           └ <function _check_contrib_params at 0x7f0011a06830>
  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/pl/patterns/_contribution_scores.py", line 31, in _check_contrib_params
    if class_labels:
       └ Index(['Mixed_Mesoderm-TileSize-100-normMethod-rc',
                'NMPs-TileSize-100-normMethod-rc', 'aPSM-TileSize-100-normMethod-r...
  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3190, in __nonzero__
    raise ValueError(

ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "/home/ldelisle/scripts/scitas_sbatchhistory/2024/20241002_tryCREest/20241016_plots_with_model.py", line 125, in <module>
    crested.pl.patterns.contribution_scores(
  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/pl/patterns/_contribution_scores.py", line 95, in contribution_scores
    _check_contrib_params(zoom_n_bases, scores, class_labels, sequence_labels)
  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/utils/_logging.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/crested/pl/patterns/_contribution_scores.py", line 31, in _check_contrib_params
    if class_labels:
  File "/scratch/izar/ldelisle/CREsted_test1/venv7/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3190, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### Version information

```
$ pip list
Package                  Version
------------------------ -----------
absl-py                  2.1.0
anndata                  0.10.9
array_api_compat         1.9
certifi                  2024.8.30
charset-normalizer       3.4.0
click                    8.1.7
contourpy                1.3.0
crested                  1.1.0
cycler                   0.12.1
docker-pycreds           0.4.0
exceptiongroup           1.2.2
filelock                 3.16.1
fonttools                4.54.1
fsspec                   2024.9.0
gitdb                    4.0.11
GitPython                3.1.43
h5py                     3.12.1
idna                     3.10
Jinja2                   3.1.4
joblib                   1.4.2
keras                    3.6.0
kiwisolver               1.4.7
logomaker                0.8
loguru                   0.7.2
markdown-it-py           3.0.0
MarkupSafe               3.0.1
matplotlib               3.9.2
mdurl                    0.1.2
ml_dtypes                0.5.0
mpmath                   1.3.0
namex                    0.0.8
natsort                  8.4.0
networkx                 3.3
numpy                    2.1.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.77
nvidia-nvtx-cu12         12.1.105
optree                   0.13.0
packaging                24.1
pandas                   2.2.3
pillow                   10.4.0
pip                      24.2
platformdirs             4.3.6
pooch                    1.8.2
protobuf                 5.28.2
psutil                   6.0.0
pybigtools               0.2.1
pyBigWig                 0.3.23
Pygments                 2.18.0
pyparsing                3.1.4
pysam                    0.22.1
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
requests                 2.32.3
rich                     13.9.2
scikit-learn             1.5.2
scipy                    1.14.1
seaborn                  0.13.2
sentry-sdk               2.16.0
setproctitle             1.3.3
setuptools               58.3.0
six                      1.16.0
smmap                    5.0.1
sympy                    1.13.3
threadpoolctl            3.5.0
torch                    2.4.1
tqdm                     4.66.5
triton                   3.0.0
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wandb                    0.18.3
wheel                    0.44.0
```

**Comment by LukasMahieu** [comment]
I can't reproduce this. Are your class_names and sequence_labels parameters both in list format? From the traceback it looks like they're an index.

You can  check with this minimal example:
```python
# 2 regions, 3 classes
scores = np.random.rand(2, 3, 100, 4)
seqs_one_hot = np.random.randint(0, 2, (2, 100, 4))
class_labels = ["A", "B", "C"]
sequence_labels = ["chr1:100-200", "chr2:200-300"]
crested.pl.patterns.contribution_scores(
    scores, seqs_one_hot, sequence_labels, class_labels
)
```

**Comment by lldelisle** [comment]
Indeed, there were indexes and this is why it was failing. Thanks.
