### ISSUE TITLE
The passed chromosome was incorrect exception when loading bigwigs

### ISSUE THREAD

**Issue by mtvector** [aertslab/CREsted#70]
### Report

Hi there, when loading bigwigs to make anndata like so:

`#You get the same error with ,chromsizes_file=genome.sizes_file
crested.import_bigwigs(bigwigs_folder=atac_bigwig_dir,regions_file=peaks_file) 
`

I get the following error:

```
21:41:37 | WARNING | Chromsizes file not provided. Will not check if regions are within chromosomes
21:41:38 | INFO | Extracting values from 24 bigWig files...
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "[/home/matthew.schmitz/Matthew/utils/miniforge3/envs/crested/lib/python3.12/concurrent/futures/process.py", line 263](https://aidc-ondemand-prd.corp.alleninstitute.org/node/n69/48920/lab/tree/Matthew/code/hmba-crossspecies-v1/analysis/atac/Matthew/utils/miniforge3/envs/crested/lib/python3.12/concurrent/futures/process.py#line=262), in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/home/matthew.schmitz/Matthew/utils/miniforge3/envs/crested/lib/python3.12/site-packages/crested/_io.py", line 78](https://aidc-ondemand-prd.corp.alleninstitute.org/node/n69/48920/lab/tree/Matthew/code/hmba-crossspecies-v1/analysis/atac/Matthew/utils/miniforge3/envs/crested/lib/python3.12/site-packages/crested/_io.py#line=77), in _extract_values_from_bigwig
    values = np.fromiter(
             ^^^^^^^^^^^^
Exception: The passed chromosome (GL456212.1) was incorrect.
"""

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 crested.import_bigwigs(bigwigs_folder=atac_bigwig_dir,regions_file='[/allen/programs/celltypes/workgroups/rnaseqanalysis/EvoGen/Team/Matthew/data/cortex_data/internal_mouse/atac/merged_peaks.bed](https://aidc-ondemand-prd.corp.alleninstitute.org/allen/programs/celltypes/workgroups/rnaseqanalysis/EvoGen/Team/Matthew/data/cortex_data/internal_mouse/atac/merged_peaks.bed)')#,chromsizes_file=genome.sizes_file

File [~/Matthew/utils/miniforge3/envs/crested/lib/python3.12/site-packages/crested/_io.py:481](https://aidc-ondemand-prd.corp.alleninstitute.org/node/n69/48920/lab/tree/Matthew/code/hmba-crossspecies-v1/analysis/atac/Matthew/utils/miniforge3/envs/crested/lib/python3.12/site-packages/crested/_io.py#line=480), in import_bigwigs(bigwigs_folder, regions_file, chromsizes_file, target, target_region_width, compress)
    471     futures = [
    472         executor.submit(
    473             _extract_values_from_bigwig,
   (...)
    478         for bw_file in bw_files
    479     ]
    480     for future in futures:
--> 481         all_results.append(future.result())
    483 if target_region_width is not None:
    484     os.remove(bed_file)

File [~/Matthew/utils/miniforge3/envs/crested/lib/python3.12/concurrent/futures/_base.py:449](https://aidc-ondemand-prd.corp.alleninstitute.org/node/n69/48920/lab/tree/Matthew/code/hmba-crossspecies-v1/analysis/atac/Matthew/utils/miniforge3/envs/crested/lib/python3.12/concurrent/futures/_base.py#line=448), in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File [~/Matthew/utils/miniforge3/envs/crested/lib/python3.12/concurrent/futures/_base.py:401](https://aidc-ondemand-prd.corp.alleninstitute.org/node/n69/48920/lab/tree/Matthew/code/hmba-crossspecies-v1/analysis/atac/Matthew/utils/miniforge3/envs/crested/lib/python3.12/concurrent/futures/_base.py#line=400), in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

Exception: The passed chromosome (GL456212.1) was incorrect.
```

You would expect this would be because of some sort of annotation mismatch... However, it appears that this contig is listed both in the bigwigs, chromsizes file and the peaks bedfile, so I'm not really sure what's going on:

```
with pybigtools.open(astro_bw_path) as f:
    print('GL456212.1' in f.chroms().keys())
```
```
True
```

```
peaks=pd.read_csv(peaks_file,sep='\t',header=None)
print(peaks)
print(peaks[0].unique())
print('GL456212.1' in peaks[0].unique())

```
```
                 0         1         2
0       GL456212.1    128566    129067
1       GL456216.1     13618     14119
2       GL456216.1     16224     16725
3       GL456216.1     17040     17541
4       GL456216.1     15641     16142
...            ...       ...       ...
566758        chrY  90806813  90807314
566759        chrY  90809237  90809738
566760        chrY  90810719  90811220
566761        chrY  90811456  90811957
566762        chrY  90812678  90813179

[566763 rows x 3 columns]
['GL456212.1' 'GL456216.1' 'GL456233.1' 'JH584292.1' 'JH584295.1'
 'JH584304.1' 'chr1' 'chr10' 'chr11' 'chr12' 'chr13' 'chr14' 'chr15'
 'chr16' 'chr17' 'chr18' 'chr19' 'chr2' 'chr3' 'chr4' 'chr5' 'chr6' 'chr7'
 'chr8' 'chr9' 'chrX' 'chrY']
True
```

Thanks so much for any thoughts!

### Version information

-----
crested             1.1.0
genomepy            0.16.1
h5py                3.12.1
pandas              2.2.3
pybigtools          0.2.2
session_info        1.0.0
torch               2.5.1
-----
PIL                 11.0.0
absl                NA
anndata             0.11.1
appdirs             1.4.4
asttokens           NA
biothings_client    0.3.1
brotli              1.1.0
certifi             2024.08.30
cffi                1.17.1
charset_normalizer  3.4.0
colorama            0.4.6
comm                0.2.2
cycler              0.12.1
cython_runtime      NA
dateutil            2.9.0.post0
debugpy             1.8.8
decorator           5.1.1
diskcache           5.6.3
distutils           3.12.7
executing           2.1.0
filelock            3.16.1
fontTools           4.55.0
fsspec              2024.10.0
gmpy2               2.1.5
hdf5plugin          5.0.0
idna                3.10
igraph              0.11.8
ipykernel           6.29.5
jaraco              NA
jedi                0.19.2
joblib              1.4.2
keras               3.6.0
kiwisolver          1.4.7
leidenalg           0.10.2
llvmlite            0.43.0
logomaker           NA
loguru              0.7.2
matplotlib          3.9.2
ml_dtypes           0.5.0
modiscolite         2.2.1
more_itertools      10.3.0
mpl_toolkits        NA
mpmath              1.3.0
mygene              3.2.2
mysql               NA
namex               NA
natsort             8.4.0
norns               NA
numba               0.60.0
numpy               2.0.0
optree              0.13.1
packaging           24.2
parso               0.8.4
pickleshare         0.7.5
pkg_resources       NA
platformdirs        4.3.6
pooch               v1.8.2
prompt_toolkit      3.0.48
psutil              6.1.0
pure_eval           0.2.3
pyBigWig            0.3.23
pycparser           2.22
pydev_ipython       NA
pydevconsole        NA
pydevd              3.2.2
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pyfaidx             0.8.1.3
pygments            2.18.0
pyparsing           3.2.0
pysam               0.22.1
pytz                2024.2
requests            2.32.3
rich                NA
scipy               1.14.1
seaborn             0.13.2
setuptools          75.5.0
six                 1.16.0
sklearn             1.5.2
socks               1.7.1
stack_data          0.6.2
sympy               1.13.1
texttable           1.7.0
threadpoolctl       3.5.0
torchgen            NA
tornado             6.4.1
tqdm                4.67.0
traitlets           5.14.3
triton              3.1.0
typing_extensions   NA
urllib3             2.2.3
wcwidth             0.2.13
yaml                6.0.2
zmq                 26.2.0
zstandard           0.23.0
-----
IPython             8.29.0
jupyter_client      8.6.3
jupyter_core        5.7.2
-----
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.28
-----
Session information updated at 2024-11-26 22:09

**Comment by mtvector** [comment]
Updating to the current commit fixed it! Looking at your PR, I suspect not every one of my bigwigs contains values for all the small contigs. Thanks for the guidance!
